# Generated by Django 4.2.13 on 2024-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDB', '0004_remove_tours_tour_dislike_remove_tours_tour_like'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_dislike',
            field=models.ManyToManyField(related_name='disliked_users', to='createDB.tours'),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_like',
            field=models.ManyToManyField(related_name='liked_users', to='createDB.tours'),
        ),
    ]
