# Generated by Django 4.2.13 on 2024-06-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createDB', '0007_alter_tours_zipcode'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='createDB.routes'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_adventure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_exhibit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_food',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_healing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_relax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_shopping',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_tour_type',
            field=models.TextField(null=True),
        ),
    ]
