# Generated by Django 4.2.13 on 2024-08-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tour_dislike_user_tour_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tour_dislike',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tour_like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_adventure',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_exhibit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_food',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_healing',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_nature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_people',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_relax',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_shopping',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
