# Generated by Django 4.2.13 on 2024-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_num', models.IntegerField()),
                ('tour_type', models.CharField(max_length=10, null=True)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Routes_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=20)),
                ('lodge', models.TextField()),
                ('route_area', models.IntegerField()),
                ('tour_startdate', models.DateTimeField(blank=True, null=True)),
                ('tour_enddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour_plan_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungucode', models.IntegerField()),
                ('addr1', models.TextField()),
                ('addr2', models.TextField()),
                ('image', models.TextField(null=True)),
                ('cat1', models.CharField(max_length=3)),
                ('cat2', models.CharField(max_length=5)),
                ('cat3', models.CharField(max_length=9)),
                ('type_id', models.IntegerField()),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('title', models.TextField(null=True)),
                ('zipcode', models.TextField(null=True)),
                ('tel', models.TextField(null=True)),
                ('eventstartdate', models.DateTimeField(null=True)),
                ('eventenddate', models.DateTimeField(null=True)),
            ],
        ),
    ]
