# Generated by Django 4.2.13 on 2024-07-22 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='tour_dislike',
            field=models.ManyToManyField(related_name='disliked_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tours',
            name='tour_like',
            field=models.ManyToManyField(related_name='liked_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour_plan_data',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.routes_plan'),
        ),
        migrations.AddField(
            model_name='tour_plan_data',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.tours'),
        ),
        migrations.AddField(
            model_name='routes_plan',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='createDB.groups'),
        ),
        migrations.AddField(
            model_name='routes_plan',
            name='route_details',
            field=models.ManyToManyField(related_name='get_routes', through='createDB.Tour_plan_data', to='createDB.tours'),
        ),
        migrations.AddField(
            model_name='routes_plan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(related_name='joined_group', through='createDB.Group_Members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group_members',
            name='disliked_plans',
            field=models.ManyToManyField(related_name='plan_dislike', to='createDB.tour_plan_data'),
        ),
        migrations.AddField(
            model_name='group_members',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createDB.groups'),
        ),
        migrations.AddField(
            model_name='group_members',
            name='liked_plans',
            field=models.ManyToManyField(related_name='plan_like', to='createDB.tour_plan_data'),
        ),
        migrations.AddField(
            model_name='group_members',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
