# Generated by Django 4.2.13 on 2024-06-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createDB', '0003_rename_group_groups_routes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routes',
            old_name='group_name',
            new_name='route_name',
        ),
    ]
