# Generated by Django 4.2.13 on 2024-06-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createDB', '0006_routes_route_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='zipcode',
            field=models.TextField(null=True),
        ),
    ]
